FROM public.ecr.aws/lambda/python:3.8

COPY tweets-to-silver-function/ ${LAMBDA_TASK_ROOT}/
COPY utils/utils.py .

RUN  pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

CMD [ "lambda_function.lambda_handler" ]
# CMD ["tail", "-f", "/dev/null"]