FROM python:3.8.13-slim

COPY processing-raw-function/unit-tests/ ./unit-tests/

COPY processing-raw-function/processing.py \
     utils/utils.py \
     ./

RUN  pip3 install pandas \
                    boto3 \
                    pytest \
                    numpy \
                    pandas \
                    requests

WORKDIR /unit-tests

CMD pytest -vv